# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andres/Documents/Universidad/telematica/battleShip/BattleShip

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andres/Documents/Universidad/telematica/battleShip/BattleShip

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andres/Documents/Universidad/telematica/battleShip/BattleShip/CMakeFiles /home/andres/Documents/Universidad/telematica/battleShip/BattleShip//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andres/Documents/Universidad/telematica/battleShip/BattleShip/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named protocol

# Build rule for target.
protocol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protocol
.PHONY : protocol

# fast build rule for target.
protocol/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol.dir/build.make CMakeFiles/protocol.dir/build
.PHONY : protocol/fast

#=============================================================================
# Target rules for targets named game_logic

# Build rule for target.
game_logic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_logic
.PHONY : game_logic

# fast build rule for target.
game_logic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic.dir/build.make CMakeFiles/game_logic.dir/build
.PHONY : game_logic/fast

#=============================================================================
# Target rules for targets named battleship_server

# Build rule for target.
battleship_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 battleship_server
.PHONY : battleship_server

# fast build rule for target.
battleship_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battleship_server.dir/build.make CMakeFiles/battleship_server.dir/build
.PHONY : battleship_server/fast

#=============================================================================
# Target rules for targets named bsclient

# Build rule for target.
bsclient: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsclient
.PHONY : bsclient

# fast build rule for target.
bsclient/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bsclient.dir/build.make CMakeFiles/bsclient.dir/build
.PHONY : bsclient/fast

#=============================================================================
# Target rules for targets named protocol_test

# Build rule for target.
protocol_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 protocol_test
.PHONY : protocol_test

# fast build rule for target.
protocol_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol_test.dir/build.make CMakeFiles/protocol_test.dir/build
.PHONY : protocol_test/fast

#=============================================================================
# Target rules for targets named game_logic_test

# Build rule for target.
game_logic_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_logic_test
.PHONY : game_logic_test

# fast build rule for target.
game_logic_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic_test.dir/build.make CMakeFiles/game_logic_test.dir/build
.PHONY : game_logic_test/fast

#=============================================================================
# Target rules for targets named phase_state_test

# Build rule for target.
phase_state_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phase_state_test
.PHONY : phase_state_test

# fast build rule for target.
phase_state_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_state_test.dir/build.make CMakeFiles/phase_state_test.dir/build
.PHONY : phase_state_test/fast

client/src/client.o: client/src/client.cpp.o
.PHONY : client/src/client.o

# target to build an object file
client/src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bsclient.dir/build.make CMakeFiles/bsclient.dir/client/src/client.cpp.o
.PHONY : client/src/client.cpp.o

client/src/client.i: client/src/client.cpp.i
.PHONY : client/src/client.i

# target to preprocess a source file
client/src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bsclient.dir/build.make CMakeFiles/bsclient.dir/client/src/client.cpp.i
.PHONY : client/src/client.cpp.i

client/src/client.s: client/src/client.cpp.s
.PHONY : client/src/client.s

# target to generate assembly for a file
client/src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bsclient.dir/build.make CMakeFiles/bsclient.dir/client/src/client.cpp.s
.PHONY : client/src/client.cpp.s

client/src/main.o: client/src/main.cpp.o
.PHONY : client/src/main.o

# target to build an object file
client/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bsclient.dir/build.make CMakeFiles/bsclient.dir/client/src/main.cpp.o
.PHONY : client/src/main.cpp.o

client/src/main.i: client/src/main.cpp.i
.PHONY : client/src/main.i

# target to preprocess a source file
client/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bsclient.dir/build.make CMakeFiles/bsclient.dir/client/src/main.cpp.i
.PHONY : client/src/main.cpp.i

client/src/main.s: client/src/main.cpp.s
.PHONY : client/src/main.s

# target to generate assembly for a file
client/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bsclient.dir/build.make CMakeFiles/bsclient.dir/client/src/main.cpp.s
.PHONY : client/src/main.cpp.s

protocol/src/game_logic.o: protocol/src/game_logic.cpp.o
.PHONY : protocol/src/game_logic.o

# target to build an object file
protocol/src/game_logic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic.dir/build.make CMakeFiles/game_logic.dir/protocol/src/game_logic.cpp.o
.PHONY : protocol/src/game_logic.cpp.o

protocol/src/game_logic.i: protocol/src/game_logic.cpp.i
.PHONY : protocol/src/game_logic.i

# target to preprocess a source file
protocol/src/game_logic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic.dir/build.make CMakeFiles/game_logic.dir/protocol/src/game_logic.cpp.i
.PHONY : protocol/src/game_logic.cpp.i

protocol/src/game_logic.s: protocol/src/game_logic.cpp.s
.PHONY : protocol/src/game_logic.s

# target to generate assembly for a file
protocol/src/game_logic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic.dir/build.make CMakeFiles/game_logic.dir/protocol/src/game_logic.cpp.s
.PHONY : protocol/src/game_logic.cpp.s

protocol/src/phase_state.o: protocol/src/phase_state.cpp.o
.PHONY : protocol/src/phase_state.o

# target to build an object file
protocol/src/phase_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol.dir/build.make CMakeFiles/protocol.dir/protocol/src/phase_state.cpp.o
.PHONY : protocol/src/phase_state.cpp.o

protocol/src/phase_state.i: protocol/src/phase_state.cpp.i
.PHONY : protocol/src/phase_state.i

# target to preprocess a source file
protocol/src/phase_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol.dir/build.make CMakeFiles/protocol.dir/protocol/src/phase_state.cpp.i
.PHONY : protocol/src/phase_state.cpp.i

protocol/src/phase_state.s: protocol/src/phase_state.cpp.s
.PHONY : protocol/src/phase_state.s

# target to generate assembly for a file
protocol/src/phase_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol.dir/build.make CMakeFiles/protocol.dir/protocol/src/phase_state.cpp.s
.PHONY : protocol/src/phase_state.cpp.s

protocol/src/protocol.o: protocol/src/protocol.cpp.o
.PHONY : protocol/src/protocol.o

# target to build an object file
protocol/src/protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol.dir/build.make CMakeFiles/protocol.dir/protocol/src/protocol.cpp.o
.PHONY : protocol/src/protocol.cpp.o

protocol/src/protocol.i: protocol/src/protocol.cpp.i
.PHONY : protocol/src/protocol.i

# target to preprocess a source file
protocol/src/protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol.dir/build.make CMakeFiles/protocol.dir/protocol/src/protocol.cpp.i
.PHONY : protocol/src/protocol.cpp.i

protocol/src/protocol.s: protocol/src/protocol.cpp.s
.PHONY : protocol/src/protocol.s

# target to generate assembly for a file
protocol/src/protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol.dir/build.make CMakeFiles/protocol.dir/protocol/src/protocol.cpp.s
.PHONY : protocol/src/protocol.cpp.s

protocol/test/game_logic_test.o: protocol/test/game_logic_test.cpp.o
.PHONY : protocol/test/game_logic_test.o

# target to build an object file
protocol/test/game_logic_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic_test.dir/build.make CMakeFiles/game_logic_test.dir/protocol/test/game_logic_test.cpp.o
.PHONY : protocol/test/game_logic_test.cpp.o

protocol/test/game_logic_test.i: protocol/test/game_logic_test.cpp.i
.PHONY : protocol/test/game_logic_test.i

# target to preprocess a source file
protocol/test/game_logic_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic_test.dir/build.make CMakeFiles/game_logic_test.dir/protocol/test/game_logic_test.cpp.i
.PHONY : protocol/test/game_logic_test.cpp.i

protocol/test/game_logic_test.s: protocol/test/game_logic_test.cpp.s
.PHONY : protocol/test/game_logic_test.s

# target to generate assembly for a file
protocol/test/game_logic_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_logic_test.dir/build.make CMakeFiles/game_logic_test.dir/protocol/test/game_logic_test.cpp.s
.PHONY : protocol/test/game_logic_test.cpp.s

protocol/test/phase_state_test.o: protocol/test/phase_state_test.cpp.o
.PHONY : protocol/test/phase_state_test.o

# target to build an object file
protocol/test/phase_state_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_state_test.dir/build.make CMakeFiles/phase_state_test.dir/protocol/test/phase_state_test.cpp.o
.PHONY : protocol/test/phase_state_test.cpp.o

protocol/test/phase_state_test.i: protocol/test/phase_state_test.cpp.i
.PHONY : protocol/test/phase_state_test.i

# target to preprocess a source file
protocol/test/phase_state_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_state_test.dir/build.make CMakeFiles/phase_state_test.dir/protocol/test/phase_state_test.cpp.i
.PHONY : protocol/test/phase_state_test.cpp.i

protocol/test/phase_state_test.s: protocol/test/phase_state_test.cpp.s
.PHONY : protocol/test/phase_state_test.s

# target to generate assembly for a file
protocol/test/phase_state_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phase_state_test.dir/build.make CMakeFiles/phase_state_test.dir/protocol/test/phase_state_test.cpp.s
.PHONY : protocol/test/phase_state_test.cpp.s

protocol/test/protocol_test.o: protocol/test/protocol_test.cpp.o
.PHONY : protocol/test/protocol_test.o

# target to build an object file
protocol/test/protocol_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol_test.dir/build.make CMakeFiles/protocol_test.dir/protocol/test/protocol_test.cpp.o
.PHONY : protocol/test/protocol_test.cpp.o

protocol/test/protocol_test.i: protocol/test/protocol_test.cpp.i
.PHONY : protocol/test/protocol_test.i

# target to preprocess a source file
protocol/test/protocol_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol_test.dir/build.make CMakeFiles/protocol_test.dir/protocol/test/protocol_test.cpp.i
.PHONY : protocol/test/protocol_test.cpp.i

protocol/test/protocol_test.s: protocol/test/protocol_test.cpp.s
.PHONY : protocol/test/protocol_test.s

# target to generate assembly for a file
protocol/test/protocol_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/protocol_test.dir/build.make CMakeFiles/protocol_test.dir/protocol/test/protocol_test.cpp.s
.PHONY : protocol/test/protocol_test.cpp.s

server/src/main.o: server/src/main.cpp.o
.PHONY : server/src/main.o

# target to build an object file
server/src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battleship_server.dir/build.make CMakeFiles/battleship_server.dir/server/src/main.cpp.o
.PHONY : server/src/main.cpp.o

server/src/main.i: server/src/main.cpp.i
.PHONY : server/src/main.i

# target to preprocess a source file
server/src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battleship_server.dir/build.make CMakeFiles/battleship_server.dir/server/src/main.cpp.i
.PHONY : server/src/main.cpp.i

server/src/main.s: server/src/main.cpp.s
.PHONY : server/src/main.s

# target to generate assembly for a file
server/src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battleship_server.dir/build.make CMakeFiles/battleship_server.dir/server/src/main.cpp.s
.PHONY : server/src/main.cpp.s

server/src/server.o: server/src/server.cpp.o
.PHONY : server/src/server.o

# target to build an object file
server/src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battleship_server.dir/build.make CMakeFiles/battleship_server.dir/server/src/server.cpp.o
.PHONY : server/src/server.cpp.o

server/src/server.i: server/src/server.cpp.i
.PHONY : server/src/server.i

# target to preprocess a source file
server/src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battleship_server.dir/build.make CMakeFiles/battleship_server.dir/server/src/server.cpp.i
.PHONY : server/src/server.cpp.i

server/src/server.s: server/src/server.cpp.s
.PHONY : server/src/server.s

# target to generate assembly for a file
server/src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/battleship_server.dir/build.make CMakeFiles/battleship_server.dir/server/src/server.cpp.s
.PHONY : server/src/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... battleship_server"
	@echo "... bsclient"
	@echo "... game_logic"
	@echo "... game_logic_test"
	@echo "... phase_state_test"
	@echo "... protocol"
	@echo "... protocol_test"
	@echo "... client/src/client.o"
	@echo "... client/src/client.i"
	@echo "... client/src/client.s"
	@echo "... client/src/main.o"
	@echo "... client/src/main.i"
	@echo "... client/src/main.s"
	@echo "... protocol/src/game_logic.o"
	@echo "... protocol/src/game_logic.i"
	@echo "... protocol/src/game_logic.s"
	@echo "... protocol/src/phase_state.o"
	@echo "... protocol/src/phase_state.i"
	@echo "... protocol/src/phase_state.s"
	@echo "... protocol/src/protocol.o"
	@echo "... protocol/src/protocol.i"
	@echo "... protocol/src/protocol.s"
	@echo "... protocol/test/game_logic_test.o"
	@echo "... protocol/test/game_logic_test.i"
	@echo "... protocol/test/game_logic_test.s"
	@echo "... protocol/test/phase_state_test.o"
	@echo "... protocol/test/phase_state_test.i"
	@echo "... protocol/test/phase_state_test.s"
	@echo "... protocol/test/protocol_test.o"
	@echo "... protocol/test/protocol_test.i"
	@echo "... protocol/test/protocol_test.s"
	@echo "... server/src/main.o"
	@echo "... server/src/main.i"
	@echo "... server/src/main.s"
	@echo "... server/src/server.o"
	@echo "... server/src/server.i"
	@echo "... server/src/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

